### PR TITLE
 Added missing string

### PR DESCRIPTION
**Pull request by mm615657**

### CODE REVIEW

**Comment by duduluu** [comment]
You are not worthy to be a translator, you are thieves and robbers!
Do not merge this please!

**Comment by UnlimitedHugs** [comment]
@duduluu 
Not sure what the issue is here. If you would rather provide your own translation, I can merge that, instead.

**Comment by mm615657** [comment]
I made this translation (i.e. few lines of missing translation)and made this pr all by myself.My obligation is limited to the part I submit,and responsible for translation quality. I have nothing to do with the translation of others.I have no idea how it comes"rob"and "thief".It is okay for me to make this pr closed if @UnlimitedHugs thinks there is anything inappropriate.

I saw an issue, I can fix it , I fixed it then I published it.I think that is how open source community works.

**Comment by UnlimitedHugs** [comment]
@mm615657 
It looks in order to me, though I cannot comment on the translated text. @duduluu did provide the original translation- but surely we can all agree to get along and share credit and opportunity.

I'm inclined to merge this if @duduluu has no objections as to the quality of the translated text.

**Comment by duduluu** [comment]
I hate vicious competition

**Comment by mm615657** [comment]
"I hate the vicious competition"
This did ridiculous. How did the word "competition" come from?
Since this is another personal attack and there is no other thing related to quality.im gonna ignore you if you have nothing else that really constructive to say.

**Comment by duduluu** [comment]
3 days ago, you join us.
We're happy for getting a new partner.
We taught you how to translate RimWorld mod.
You're studious, we trusted you're a good guy.
Yesterday, Yyou said you don't care who is working on one translation and will commit the translation to auithor, even it is confilcted to other.
You finally tear off the camouflage, malicious competitor

**Comment by mm615657** [comment]
You triggered me.
I am a game developer.I have other projects on Github and some of them are also translation works way before the mysterious"3 days".I have full awerness of what was i am doing.what u said makes ur self an great leaders leading the entire community,which is not accetpable. All knowledge I learn comes from internet and University, not from any single person but continuous learning,while you are not in my list.This mod is easy to modify since it is open sourced and no nested-in string.There is no reason I would go to seek help from anyone specific.

**Comment by duduluu** [comment]
You said the mods all are open source, but you said other translator are piracy. How contradictory, haha.

**Comment by mm615657** [comment]
There is no evidence whatsoever of what you are saying, even not reasonable.
what i have done is ADDED missing lines,not modify anything.

**Comment by mm615657** [comment]
I have no idea what are you talking about and what u said strongly confused me.

**Comment by UnlimitedHugs** [comment]
Allright. I merged both, so @mm615657 can get credit for the contribution.
However, @duduluu gets priority for providing a more complete translation.
The same goes for your pull requests on Allow Tool.
Please avoid creating drama in the future.

**Comment by duduluu** [comment]
@UnlimitedHugs Sorry for this time.
I'm just trying to protect other translators. Not for my translation.
It's welcome to everyone to instead my translation by his better translation, but mm615657

but, ....emmmm, it's completed I did at A17, but you add some new text to this mod B18.

**Pull request merged**
